### ISSUE TITLE
52 packs are using an ancient thus not-supported-by-all compressing algorithm

### ISSUE THREAD

**Issue by Chaiavi** [sixteencolors/sixteencolors-archive#41]
Please look at the issue submitted on [pyAns](https://github.com/sairuk/pyANS/issues/13)

When Zip began its days (early 199x) it had an old packaging algorithm: Implode/Shrink.

It was later on replaced by more advanced algorithms in the internal zip code.

As it became rare and unused it was [dropped by the Zip module in Python](https://github.com/sairuk/pyANS/issues/13#issuecomment-1112120240) (As well as in many other places).

The 16colors packages are old, thus 52 of the thousands of packages use the old algorithm which can't be used by many systems (and will probably will get less support with time).

So my question here is: What do you think about repackaging [these 52 art packages](https://github.com/sairuk/pyANS/blob/master/pack_info/unsupported.md) ?

From the one side we will lose the original packaged file :-(
But on the other hand many more people will be able to actually use the art-package contents of them :-)

**Comment by sairuk** [comment]
I took a bit more of a look and imo the loss of the comment art (and release integrity) is why repacks should never end up this archive

e.g.

```

Archive:  1995/spas9508.zip

 ________ ________ __________________________   ___ ____ ________ ____ _____
(_____   |   ___  | _____/     (_____   |    | |   |    |   ___  |    |  ___)
 |   |   |   \____||    |   |___|   |   |    |_|______  |   \____||___|  _)__
 |       |    | |  |    |   |   |       |    '    |  |  |    |        | .    |
_|___|   |____| |_______|___    |___|   |____     |   __|____|___|    |_|    |_
     |___|                 |____|   |___|    |____|__|           |____| |____|
.                                                                             .
:  apocalypse � 2o1.934.5613 � sys: napalm � cia united states headquarters   :
|                                                                             |
+--------------------------------------------------------------------[pl�cia]-+
  exploding: 0895MEMB.ANS            
  exploding: 0895NEWS.ANS            
  exploding: BD!REV.ANS              
  exploding: CP!LOGOS.ANS            
 extracting: SVU_V1.ZIP  
```

I'd like to keep this comment art around but for transparency it does look like `vodpack1.zip` probably isn't the original up either

```
Archive:  1993/vodpak1.zip
This file was leeched from ...
      ������������  ���������  ������������  ���������  ����
����� ������������ ����������� ������������ ����������� ���� �����������������
��������� ���� ��� ��� ��� ��� ��� ���� ��� ����������� ���� �����������������
��������� ���� ��� ��� ��� ��� ��� ���� ��� ����������� ���� �����������������
��������� ���� ��� ����������� ��� ���� ��� ���� � ���� ����������� ����������
          ����      ���������      ����     ����   ����  ����������
   SysOp            9600+ need only apply!     [ 203.354.8095 ]
   Arachknight      2400 by invitation only!   [ 203.354.8095 ]
        ���������   ���   ���   ���������   ���������   ���������
������ �����  ���� ���� � ���� ����������� ����������� ����� ����� �����������
������ ���� ������ ����������� ����������� ��� ��� ��� ��������   ������������
������ ���� ������ ����������� ����������� ��� ��� ���    �������� �����������
������ �����  ���� ���� � ���� ����   ���� ����������� ����� ����� �����������
        ���������   ���   ���  ����   ����  ���������   ���������
  Length      Date    Time    Name
---------  ---------- -----   ----
```

**Comment by Chaiavi** [comment]
@sairuk obviously we all won't want to lose the original meta data.

Is it possible to repack these archives while maintaining the original meta data ?

**Comment by bart-d** [comment]
I don't see the necessity of repackaging artpacks just because of the compression method. There are even other compression methods used for certain pack in the archive which may or may not be still supported. As mentioned above, this is an issue for the tools to address and should not be solved by modifying historic content.

This is a bit similar to Firefox not supporting the display of GIF files saved in specifically GIF87a, it's not that we're going to reconvert them to a more recent GIF format and repackage the files. And further down the same logic one could argue the artpacks should be repackaged with all .ANS converted to .PNG because no viewers are readily available on modern operating system nor do their consoles support output identical to ANSI.SYS.
